const translations = {
  en: {
    skip:"Skip to content", brand:"Upper Air Observers", brandFa:"پایشگران جو بالا",
    navSystem:"System", navRadiosonde:"DigiSonde", navGround:"Ground Station", navSoftware:"DigiMon", navField:"Field Work", navDownloads:"Downloads", navContact:"Contact",
    heroKicker:"UPPER-AIR SOUNDING SYSTEMS", heroTitle:"DigiSonde.<br>From balloon launch to atmospheric profile.", heroLead:"A complete upper-air observation workflow built around the DigiSonde radiosonde, field-ready receiving hardware and DigiMon ground-station software.", heroPrimary:"Explore the system", heroSecondary:"View catalogues", fact1:"DigiSonde radiosonde", fact2:"Ground-station hardware", fact3:"DigiMon software",
    systemKicker:"ONE SOUNDING CHAIN", systemTitle:"Radiosonde, receiving hardware and sounding software — designed to work as one system.", systemLead:"The DigiSonde measures atmospheric parameters aloft and sends telemetry by radio. The ground station receives the downlink and DigiMon supports the operational sounding workflow, from a new sounding through profile comparison and TEMP generation.",
    sondeTag:"AIRBORNE INSTRUMENT", sondeCardTitle:"DigiSonde® Radiosonde", sondeCardText:"Balloon-borne PTU and GNSS telemetry for building a vertical atmospheric profile during ascent.", learnSonde:"Product details →",
    groundTag:"FIELD HARDWARE", groundCardTitle:"Ground Station", groundCardText:"Receiving antennas, station electronics and portable field hardware for real-time radiosonde telemetry reception.", learnGround:"Hardware details →",
    softwareTag:"OPERATIONS & DATA", softwareCardTitle:"DigiMon® Software", softwareCardText:"Sounding control, ground check, TEMP generation, ascent comparison and profile comparison in one operational interface.", learnSoftware:"Software details →",
    dsKicker:"DIGISONDE®", dsTitle:"Upper-air telemetry for PTU and wind observations", dsText:"DigiSonde is carried aloft by a weather balloon, measures atmospheric variables and transmits the observations to the ground station by radio. The integrated GNSS module provides accurate positioning and supports wind calculation, while pressure, temperature, relative humidity and wind observations are used to form the vertical atmospheric profile.", actualProduct:"Actual product photo", iranFlightCap:"DigiSonde over Iran during high-altitude flight", pressureRange:"hPa pressure range", temperatureRange:"°C temperature range", humidityRange:"% RH range", measurementRate:"measurement rate", ptuHead:"PTU measurement", pressure:"Pressure", temperature:"Temperature", humidity:"Relative humidity", txHead:"Telemetry & general", frequency:"Frequency", output:"Output power", modulation:"Modulation", weight:"Weight", inclBattery:"including batteries", windHead:"Wind measurement", specEditHint:"You can edit the numbers later directly in the table cells below.", specParam:"Parameter", specRange:"Range", specResolution:"Resolution", specAccuracy:"Accuracy", specMetric:"Metric", specValue:"Value", windSpeedResolution:"Wind speed resolution", windSpeedAccuracy:"Wind speed accuracy", windDirectionResolution:"Wind direction resolution", windDirectionAccuracy:"Wind direction accuracy", positionResolution:"Position resolution", positionAccuracy:"Position accuracy", windCalculation:"Wind calculation", measurementRateLabel:"Measurement rate", ptuIcon1:"Pressure", ptuIcon2:"Temperature", ptuIcon3:"Humidity", windIcon1:"GNSS", windIcon2:"Wind", windIcon3:"Position", txIcon1:"RF link", txIcon2:"Power", txIcon3:"Telemetry", specNote:"Specifications shown here are taken from the supplied DigiSonde catalogue.",
    groundKicker:"GROUND-STATION HARDWARE", groundTitle:"Portable and fixed receiving hardware for operational upper-air sounding", groundText:"The Upper Air Observers ground-station hardware includes the receiving antenna, receiver electronics, GPS antenna and a dedicated ground-check box for pre-launch verification. It is available as a portable field configuration and as a fixed receiving installation.", groundStep1:"Ground check", groundStep1Text:"Verify radiosonde operation before launch using the ground-check box", groundStep2:"Receive & track", groundStep2Text:"Capture DigiSonde telemetry and track the ascent in real time", groundStep3:"Operate in field or fixed mode", groundStep3Text:"Deploy as a rugged portable station or as a permanent receiving installation", portableCaption:"Portable dual receiving-station setup in field operation", fixedCaption:"Receiving antenna with ground-check box at the launch site", groundSpecKicker:"GROUND-STATION SPECIFICATIONS", groundSpecTitle:"Key operational specifications", groundSpecText:"Main technical points for the receiving hardware and its pre-launch support functions.", groundSpecHead:"System overview", groundSpecNote:"You can edit the values later directly in the table cells below.", groundSpec1:"System configuration", groundSpec1Val:"Portable field station and fixed receiving installation", groundSpec2:"Receiving frequency range", groundSpec3:"Operational range", groundSpec4:"Included modules", groundSpec4Val:"Receiving antenna, receiver electronics, GPS antenna, ground-check box", groundSpec5:"Ground-check function", groundSpec5Val:"Pre-launch verification of radiosonde operation and link integrity",
    softwareKicker:"DIGIMON® GROUND STATION & SOUNDING SOFTWARE", softwareTitle:"The operational interface for a sounding campaign", softwareText:"DigiMon integrates radiosonde operations, ground validation and atmospheric profile analysis into a unified workflow. The software supports ground check procedures, real-time telemetry monitoring, live parameter graphs, simulation profiles, Skew-T log-P diagram generation, post-processing corrections and generation of meteorological output products including WMO-standard TEMP messages.", groundCheckLabel:"Ground Check", skewtLabel:"Skew-T Profile", telemetryLabel:"Real-time telemetry", parameterLabel:"Real-time parameter graphs", softwareF1:"New sounding workflow", softwareF2:"Ground check and station position", softwareF3:"Simulation profiles", softwareF4:"Generate WMO-standard TEMP output", softwareF5:"Compare ascents and profiles", softwareF6:"User and system settings", softwareF7:"Real-time telemetry data and live parameter graphs", softwareF8:"Skew-T log-P profile generation", softwareF9:"Post-processing corrections and quality control",
    chainKicker:"MEASUREMENT FLOW", chainTitle:"From the balloon to usable meteorological data", chain1:"Balloon ascent", chain1Text:"DigiSonde rises through the atmosphere", chain2:"PTU + GNSS", chain2Text:"Atmospheric and position observations", chain3:"Radio downlink", chain3Text:"Telemetry transmitted to the ground", chain4:"Ground station", chain4Text:"Receiving and station hardware", chain5:"DigiMon", chain5Text:"Sounding, comparison and output workflow",
    comparisonKicker:"DIGISONDE IN THE FIELD", comparisonTitle:"Built for real-world upper-air operations", comparisonLead:"From launch preparation to balloon-borne ascent, DigiSonde is designed for practical upper-air sounding operations. These field photographs show DigiSonde deployed alongside established radiosonde platforms during operational sounding activities.", comparisonCap1:"DigiSonde alongside M20 and iMet-2 radiosondes", comparisonCap2:"DigiSonde alongside GRAW DFM-17 radiosonde",
    flightKicker:"ACTUAL FLIGHT IMAGERY", flightTitle:"Your DigiSonde shown from pre-launch setup to near-space flight.", flightLead:"These added photos show the actual Upper Air Observers radiosonde in comparative test preparation on the runway and during flight at high altitude.", flightCap1:"Runway preparation with the Upper Air Observers DigiSonde", flightCap2:"Actual DigiSonde in flight above the clouds", flightCap3:"High-altitude view during DigiSonde ascent",
    fieldKicker:"FIELD & COMPARATIVE TESTING", fieldTitle:"Hardware shown in real sounding preparation and test environments", fieldLead:"These photographs are from Upper Air Observers development and field work. One image shows comparative preparation with a GRAW radiosonde; no performance claim is implied by the photograph.", fieldCap1:"Balloon preparation before sounding", fieldCap2:"Comparative preparation with a GRAW radiosonde", fieldCap3:"Portable station hardware and DigiSonde units", fieldCap4:"Field receiving antenna setup",
    appKicker:"APPLICATION AREAS", appTitle:"Upper-air measurements for operational weather and atmospheric work", appLead:"The supplied UAO catalogue identifies meteorology, transportation and energy as application areas, with sounding data supporting organizations such as meteorological institutes, airports and airlines, transport authorities and renewable-energy operators.", app1:"Meteorology", app1Text:"Vertical atmospheric observations for operational analysis and forecasting workflows.", app2:"Transportation", app2Text:"Upper-air information relevant to aviation and other weather-sensitive transport operations.", app3:"Energy", app3Text:"Atmospheric observations for weather-sensitive energy and renewable-energy activities.",
    downloadsKicker:"DOCUMENTATION", downloadsTitle:"DigiSonde product material", downloadsLead:"The documents below are the supplied Upper Air Observers catalogues used as the technical source for this product introduction.", doc1:"DigiSonde catalogue — Persian", doc2:"DigiSonde applications — English", doc3:"DigiSonde specifications — English",
    contactKicker:"UPPER AIR OBSERVERS", contactTitle:"Upper-air observation systems from Tehran, Iran.", contactText:"For DigiSonde radiosondes, ground-station hardware, DigiMon software or technical cooperation, contact Upper Air Observers.", locationLabel:"LOCATION", location:"Tehran, Iran", emailLabel:"EMAIL", linkedinLabel:"LINKEDIN", webLabel:"WEB", companyLabel:"COMPANY", companyName:"Upper Air Observers / پایشگران جو بالا", footerLocation:"Tehran, Iran", backTop:"Back to top ↑", heroSecondaryAlt:"See product pages", openPage:"Open page →", backHome:"Back to homepage", pageSondeTitle:"DigiSonde radiosonde", pageSondeLead:"A high-performance upper-air radiosonde designed for atmospheric profiling. DigiSonde integrates PTU sensors, GNSS positioning and digital telemetry to provide accurate meteorological observations from balloon-borne soundings.", pageGroundTitle:"Ground-station hardware", pageGroundLead:"Portable and fixed receiving hardware with receiving antenna, receiver electronics, GPS antenna and ground-check box for operational sounding.", pageSoftwareTitle:"DigiMon sounding software", pageSoftwareLead:"An operational sounding software suite for ground check, real-time telemetry monitoring, WMO-standard TEMP output, Skew-T profile generation, simulation profiles and post-processing corrections.", softwarePageSub:"Operational tools for sounding, checking, comparing and reporting", softwarePageLead:"DigiMon serves as the operational software layer that ties together ground-check, telemetry monitoring, sounding control, correction workflows and reporting tasks for the complete upper-air system."
  },
  // Persian translations: edit only the values in this section when updating the Farsi website text.
  fa: {
    skip:"رفتن به محتوای اصلی", brand:"پایشگران جو بالا", brandFa:"Upper Air Observers",
    navSystem:"سامانه", navRadiosonde:"دیجی‌سوند", navGround:"ایستگاه زمینی", navSoftware:"دیجی‌مان", navField:"فعالیت میدانی", navDownloads:"دانلودها", navContact:"تماس",
    heroKicker:"سامانه‌های سونداژ جو بالا", heroTitle:"دیجی‌سوند.<br>از پرتاب بالن تا پروفیل جو.", heroLead:"یک زنجیره کامل پایش جو بالا شامل رادیوسوند دیجی‌سوند، سخت‌افزار دریافت میدانی و نرم‌افزار ایستگاه زمینی دیجی‌مان.", heroPrimary:"مشاهده سامانه", heroSecondary:"مشاهده کاتالوگ‌ها", fact1:"رادیوسوند دیجی‌سوند", fact2:"سخت‌افزار ایستگاه زمینی", fact3:"نرم‌افزار دیجی‌مان",
    systemKicker:"یک زنجیره کامل سونداژ", systemTitle:"رادیوسوند، سخت‌افزار دریافت و نرم‌افزار سونداژ؛ اجزای یک سامانه یکپارچه.", systemLead:"دیجی‌سوند پارامترهای جوی را در ارتفاع اندازه‌گیری و داده‌ها را از طریق رادیو ارسال می‌کند. ایستگاه زمینی سیگنال را دریافت می‌کند و دیجی‌مان فرآیند عملیاتی سونداژ، مقایسه پروفیل‌ها و تولید TEMP را پشتیبانی می‌کند.",
    sondeTag:"ابزار پروازی", sondeCardTitle:"رادیوسوند DigiSonde®", sondeCardText:"اندازه‌گیری PTU و GNSS با حمل توسط بالن برای تشکیل پروفیل عمودی جو در طول صعود.", learnSonde:"جزئیات محصول ←",
    groundTag:"سخت‌افزار میدانی", groundCardTitle:"ایستگاه زمینی", groundCardText:"آنتن‌های دریافت، تجهیزات ایستگاه و سخت‌افزار قابل حمل برای دریافت بلادرنگ تله‌متری رادیوسوند.", learnGround:"جزئیات سخت‌افزار ←",
    softwareTag:"عملیات و داده", softwareCardTitle:"نرم‌افزار DigiMon®", softwareCardText:"کنترل سونداژ، گراند چک، تولید TEMP و مقایسه صعودها و پروفیل‌ها در یک رابط عملیاتی.", learnSoftware:"جزئیات نرم‌افزار ←",
    dsKicker:"DIGISONDE®", dsTitle:"تله‌متری جو بالا برای اندازه‌گیری PTU و باد", dsText:"دیجی‌سوند توسط بالن هواشناسی به لایه‌های بالاتر جو حمل می‌شود، پارامترهای جوی را اندازه‌گیری کرده و داده‌ها را از طریق رادیو به ایستگاه زمینی ارسال می‌کند. ماژول یکپارچه GNSS موقعیت‌یابی دقیق را فراهم کرده و از محاسبه باد پشتیبانی می‌کند، در حالی که داده‌های فشار، دما، رطوبت نسبی و باد برای تشکیل پروفیل عمودی جو به‌کار می‌روند.", actualProduct:"تصویر واقعی محصول", iranFlightCap:"دیجی‌سوند بر فراز ایران در پرواز ارتفاع بالا", pressureRange:"هکتوپاسکال بازه فشار", temperatureRange:"درجه سلسیوس بازه دما", humidityRange:"درصد بازه رطوبت نسبی", measurementRate:"نرخ اندازه‌گیری", ptuHead:"اندازه‌گیری PTU", pressure:"فشار", temperature:"دما", humidity:"رطوبت نسبی", txHead:"تله‌متری و مشخصات عمومی", frequency:"فرکانس", output:"توان خروجی", modulation:"مدولاسیون", weight:"وزن", inclBattery:"با احتساب باتری", windHead:"اندازه‌گیری باد", specEditHint:"بعداً می‌توانید اعداد را مستقیماً در سلول‌های جدول زیر ویرایش کنید.", specParam:"پارامتر", specRange:"بازه", specResolution:"تفکیک‌پذیری", specAccuracy:"دقت", specMetric:"مشخصه", specValue:"مقدار", windSpeedResolution:"تفکیک‌پذیری سرعت باد", windSpeedAccuracy:"دقت سرعت باد", windDirectionResolution:"تفکیک‌پذیری جهت باد", windDirectionAccuracy:"دقت جهت باد", positionResolution:"تفکیک‌پذیری موقعیت", positionAccuracy:"دقت موقعیت", windCalculation:"روش محاسبه باد", measurementRateLabel:"نرخ اندازه‌گیری", ptuIcon1:"فشار", ptuIcon2:"دما", ptuIcon3:"رطوبت", windIcon1:"GNSS", windIcon2:"باد", windIcon3:"موقعیت", txIcon1:"لینک RF", txIcon2:"توان", txIcon3:"تله‌متری", specNote:"مشخصات نمایش‌داده‌شده از کاتالوگ ارائه‌شده دیجی‌سوند استخراج شده‌اند.",
    groundKicker:"سخت‌افزار ایستگاه زمینی", groundTitle:"سخت‌افزار دریافت قابل‌حمل و ثابت برای سونداژ عملیاتی جو بالا", groundText:"سخت‌افزار ایستگاه زمینی پایشگران جو بالا شامل آنتن دریافت، تجهیزات گیرنده، آنتن GPS و یک گراندچک باکس اختصاصی برای بررسی پیش از پرتاب است. این سامانه هم به‌صورت پیکربندی قابل‌حمل میدانی و هم به‌صورت نصب ثابت ارائه می‌شود.", groundStep1:"گراند چک", groundStep1Text:"بررسی عملکرد رادیوسوند پیش از پرتاب با استفاده از گراندچک باکس", groundStep2:"دریافت و رهگیری", groundStep2Text:"دریافت تله‌متری دیجی‌سوند و رهگیری صعود به‌صورت بلادرنگ", groundStep3:"عملیات میدانی یا ثابت", groundStep3Text:"استقرار به‌صورت ایستگاه مقاوم قابل‌حمل یا نصب دائم دریافت", portableCaption:"چیدمان دو ایستگاه دریافت در عملیات میدانی", fixedCaption:"آنتن دریافت به‌همراه گراندچک باکس در محل پرتاب", groundSpecKicker:"مشخصات ایستگاه زمینی", groundSpecTitle:"مشخصات کلیدی عملیاتی", groundSpecText:"نکات فنی اصلی برای سخت‌افزار دریافت و عملکردهای پشتیبانی پیش از پرتاب.", groundSpecHead:"نمای کلی سامانه", groundSpecNote:"بعداً می‌توانید مقادیر را مستقیماً در سلول‌های جدول زیر ویرایش کنید.", groundSpec1:"پیکربندی سامانه", groundSpec1Val:"ایستگاه میدانی قابل‌حمل و نصب ثابت دریافت", groundSpec2:"بازه فرکانس دریافت", groundSpec3:"برد عملیاتی", groundSpec4:"ماژول‌های شامل", groundSpec4Val:"آنتن دریافت، تجهیزات گیرنده، آنتن GPS، گراندچک باکس", groundSpec5:"عملکرد گراند چک", groundSpec5Val:"بررسی پیش از پرتاب برای اطمینان از عملکرد رادیوسوند و سلامت لینک",
    softwareKicker:"نرم‌افزار ایستگاه زمینی و سونداژ DIGIMON®", softwareTitle:"رابط عملیاتی برای یک عملیات سونداژ", softwareText:"دیجی‌مان عملیات رادیوسوند، اعتبارسنجی زمینی و تحلیل پروفیل‌های جوی را در یک چرخه یکپارچه جمع می‌کند. این نرم‌افزار از گراند چک، پایش بلادرنگ تله‌متری، نمودارهای زنده پارامترها، پروفیل‌های شبیه‌سازی، تولید نمودار Skew-T Log-P، تصحیحات پس‌پردازش و تولید خروجی‌های هواشناسی شامل پیام‌های TEMP استاندارد WMO پشتیبانی می‌کند.", groundCheckLabel:"گراند چک", skewtLabel:"پروفیل Skew-T", telemetryLabel:"تله‌متری بلادرنگ", parameterLabel:"نمودارهای بلادرنگ پارامترها", softwareF1:"فرآیند سونداژ جدید", softwareF2:"گراند چک و موقعیت ایستگاه", softwareF3:"پروفیل‌های شبیه‌سازی", softwareF4:"تولید خروجی TEMP استاندارد WMO", softwareF5:"مقایسه صعودها و پروفیل‌ها", softwareF6:"تنظیمات سامانه و کاربران", softwareF7:"تله‌متری بلادرنگ و نمودارهای زنده پارامترها", softwareF8:"تولید پروفیل Skew-T Log-P", softwareF9:"تصحیحات پس‌پردازش و کنترل کیفیت",
    chainKicker:"جریان اندازه‌گیری", chainTitle:"از بالن تا داده هواشناسی قابل استفاده", chain1:"صعود بالن", chain1Text:"دیجی‌سوند در جو صعود می‌کند", chain2:"PTU + GNSS", chain2Text:"اندازه‌گیری‌های جوی و موقعیت", chain3:"لینک رادیویی", chain3Text:"ارسال تله‌متری به سطح زمین", chain4:"ایستگاه زمینی", chain4Text:"آنتن و تجهیزات دریافت", chain5:"دیجی‌مان", chain5Text:"سونداژ، مقایسه و تولید خروجی",
    comparisonKicker:"دیجی‌سوند در میدان", comparisonTitle:"طراحی‌شده برای عملیات واقعی جو بالا", comparisonLead:"از آماده‌سازی پیش از پرتاب تا صعود با بالون، دیجی‌سوند برای عملیات عملی سونداژ جو بالا طراحی شده است. این تصاویر میدانی، دیجی‌سوند را در کنار سامانه‌های شناخته‌شده رادیوسوند در جریان عملیات سونداژ نشان می‌دهند.", comparisonCap1:"دیجی‌سوند در کنار رادیوسوندهای M20 و iMet-2", comparisonCap2:"دیجی‌سوند در کنار رادیوسوند GRAW DFM-17",
    flightKicker:"تصاویر واقعی پرواز", flightTitle:"دیجی‌سوند شما از آماده‌سازی پیش از پرتاب تا پرواز در نزدیکی فضا.", flightLead:"این تصاویر افزوده‌شده، رادیوسوند واقعی پایشگران جو بالا را در آماده‌سازی مقایسه‌ای روی باند و همچنین در پرواز در ارتفاع بالا نشان می‌دهند.", flightCap1:"آماده‌سازی روی باند با دیجی‌سوند پایشگران جو بالا", flightCap2:"دیجی‌سوند واقعی در حال پرواز بر فراز ابرها", flightCap3:"نمای ارتفاع بالا در جریان صعود دیجی‌سوند",
    fieldKicker:"آزمون‌های میدانی و مقایسه‌ای", fieldTitle:"تجهیزات در محیط واقعی آماده‌سازی سونداژ و آزمون", fieldLead:"این تصاویر مربوط به توسعه و فعالیت‌های میدانی پایشگران جو بالا هستند. در یکی از تصاویر آماده‌سازی مقایسه‌ای با یک رادیوسوند GRAW دیده می‌شود؛ این تصویر به‌تنهایی بیانگر ادعای عملکردی نیست.", fieldCap1:"آماده‌سازی بالن پیش از سونداژ", fieldCap2:"آماده‌سازی مقایسه‌ای با رادیوسوند GRAW", fieldCap3:"تجهیزات ایستگاه قابل حمل و واحدهای دیجی‌سوند", fieldCap4:"چیدمان آنتن دریافت در میدان",
    appKicker:"حوزه‌های کاربرد", appTitle:"اندازه‌گیری جو بالا برای عملیات هواشناسی و فعالیت‌های جوی", appLead:"کاتالوگ ارائه‌شده UAO هواشناسی، حمل‌ونقل و انرژی را به‌عنوان حوزه‌های کاربرد معرفی می‌کند و به استفاده از داده‌های هواشناسی توسط مؤسسات هواشناسی، فرودگاه‌ها و خطوط هوایی، مجموعه‌های حمل‌ونقل و فعالان انرژی‌های تجدیدپذیر اشاره دارد.", app1:"هواشناسی", app1Text:"مشاهدات عمودی جو برای تحلیل عملیاتی و فرآیندهای پیش‌بینی.", app2:"حمل‌ونقل", app2Text:"اطلاعات جو بالا برای هوانوردی و سایر عملیات حمل‌ونقل وابسته به شرایط جوی.", app3:"انرژی", app3Text:"مشاهدات جوی برای فعالیت‌های انرژی و انرژی‌های تجدیدپذیر حساس به هوا.",
    downloadsKicker:"مستندات", downloadsTitle:"مستندات محصول دیجی‌سوند", downloadsLead:"اسناد زیر کاتالوگ‌های ارائه‌شده پایشگران جو بالا هستند و به‌عنوان منبع فنی این معرفی محصول استفاده شده‌اند.", doc1:"کاتالوگ دیجی‌سوند — فارسی", doc2:"کاربردهای دیجی‌سوند — انگلیسی", doc3:"مشخصات دیجی‌سوند — انگلیسی",
    contactKicker:"پایشگران جو بالا", contactTitle:"سامانه‌های پایش جو بالا از تهران، ایران.", contactText:"برای رادیوسوند دیجی‌سوند، سخت‌افزار ایستگاه زمینی، نرم‌افزار دیجی‌مان یا همکاری فنی با پایشگران جو بالا تماس بگیرید.", locationLabel:"موقعیت", location:"تهران، ایران", emailLabel:"ایمیل", linkedinLabel:"لینکدین", webLabel:"وب", companyLabel:"شرکت", companyName:"پایشگران جو بالا / Upper Air Observers", footerLocation:"تهران، ایران", backTop:"بازگشت به بالا ↑", heroSecondaryAlt:"مشاهده صفحات محصولات", openPage:"ورود به صفحه ←", backHome:"بازگشت به صفحه اصلی", pageSondeTitle:"رادیوسوند دیجی‌سوند", pageSondeLead:"رادیوسوند حرفه‌ای پایش جو بالا برای تهیه پروفیل‌های دقیق جوی. دیجی‌سوند با حسگرهای PTU، موقعیت‌یابی GNSS و تله‌متری دیجیتال، داده‌های هواشناسی را از طریق پرواز بالن ارائه می‌کند.", pageGroundTitle:"سخت‌افزار ایستگاه زمینی", pageGroundLead:"سخت‌افزار دریافت قابل‌حمل و ثابت همراه با آنتن دریافت، تجهیزات گیرنده، آنتن GPS و گراندچک باکس برای سونداژ عملیاتی.", pageSoftwareTitle:"نرم‌افزار سونداژ دیجی‌مان", pageSoftwareLead:"یک مجموعه نرم‌افزار عملیاتی برای گراند چک، پایش بلادرنگ تله‌متری، خروجی TEMP استاندارد WMO، تولید پروفیل Skew-T، پروفیل‌های شبیه‌سازی و تصحیحات پس‌پردازش.", softwarePageSub:"ابزارهای عملیاتی برای سونداژ، بررسی، مقایسه و گزارش‌گیری", softwarePageLead:"دیجی‌مان لایه نرم‌افزاری عملیاتی سامانه است که گراندچک، پایش تله‌متری، کنترل سونداژ، فرآیندهای تصحیح و وظایف گزارش‌گیری را برای سامانه کامل جو بالا به‌هم متصل می‌کند."
  }
};

const root=document.documentElement, body=document.body;
const langButtons=[...document.querySelectorAll('.lang-btn')];
function setLanguage(lang){
  const dict=translations[lang]||translations.en;
  root.lang=lang; root.dir=lang==='fa'?'rtl':'ltr'; body.classList.toggle('fa',lang==='fa');
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k]!==undefined)el.innerHTML=dict[k]});
  langButtons.forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));
  try{localStorage.setItem('uao-lang',lang)}catch(e){}
}
langButtons.forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
// Smooth back-to-top navigation
document.querySelectorAll('a[href="#top"]').forEach(btn=>{
  btn.addEventListener('click',e=>{
    e.preventDefault();
    window.scrollTo({top:0,behavior:'smooth'});
  });
});

const menuBtn=document.querySelector('.menu-toggle'), nav=document.querySelector('.main-nav');
menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
document.getElementById('year').textContent=new Date().getFullYear();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
let preferred='en';try{preferred=localStorage.getItem('uao-lang')||(navigator.language?.toLowerCase().startsWith('fa')?'fa':'en')}catch(e){}
setLanguage(preferred);
