const translations = {
  en: {
    skip:"Skip to content", brand:"Upper Air Observers", brandFa:"پایشگران جو بالا",
    navSystem:"System", navRadiosonde:"DigiSonde", navGround:"Ground Station", navSoftware:"DigiMon", navField:"Field Work", navDownloads:"Downloads", navContact:"Contact",
    heroKicker:"UPPER-AIR SOUNDING SYSTEMS", heroTitle:"DigiSonde.<br>From balloon launch to atmospheric profile.", heroLead:"A complete upper-air observation workflow built around the DigiSonde radiosonde, field-ready receiving hardware and DigiMon ground-station software.", heroPrimary:"Explore the system", heroSecondary:"View catalogues", fact1:"DigiSonde radiosonde", fact2:"Ground-station hardware", fact3:"DigiMon software",
    systemKicker:"ONE SOUNDING CHAIN", systemTitle:"Radiosonde, receiving hardware and sounding software — designed to work as one system.", systemLead:"The DigiSonde measures atmospheric parameters aloft and sends telemetry by radio. The ground station receives the downlink and DigiMon supports the operational sounding workflow, from a new sounding through profile comparison and TEMP generation.",
    sondeTag:"AIRBORNE INSTRUMENT", sondeCardTitle:"DigiSonde® Radiosonde", sondeCardText:"Balloon-borne PTU and GNSS telemetry for building a vertical atmospheric profile during ascent.", learnSonde:"Product details →",
    groundTag:"FIELD HARDWARE", groundCardTitle:"Ground Station", groundCardText:"Receiving antennas, station electronics and portable field hardware for real-time radiosonde telemetry reception.", learnGround:"Hardware details →",
    softwareTag:"OPERATIONS & DATA", softwareCardTitle:"DigiMon® Software", softwareCardText:"Sounding control, simulation, TEMP generation, ascent comparison and profile comparison in one operational interface.", learnSoftware:"Software details →",
    dsKicker:"DIGISONDE®", dsTitle:"Upper-air telemetry for PTU and wind observations", dsText:"DigiSonde is carried aloft by a weather balloon, measures atmospheric variables and transmits the observations to the ground station by radio. Pressure, temperature, relative humidity and wind are used to form the vertical atmospheric profile.", actualProduct:"Actual product photo", pressureRange:"hPa pressure range", temperatureRange:"°C temperature range", humidityRange:"% RH range", measurementRate:"measurement rate", ptuHead:"PTU measurement", pressure:"Pressure", temperature:"Temperature", humidity:"Relative humidity", txHead:"Telemetry & general", frequency:"Frequency", output:"Output power", modulation:"Modulation", weight:"Weight", inclBattery:"including batteries", specNote:"Specifications shown here are taken from the supplied DigiSonde catalogue.",
    groundKicker:"GROUND-STATION HARDWARE", groundTitle:"Built for radiosonde reception in fixed and portable field setups", groundText:"The complete sounding chain includes a downlink receiving antenna, ground-station electronics and a GPS antenna. The photographs below show Upper Air Observers hardware in portable field operation and a fixed receiving installation.", groundStep1:"Receive", groundStep1Text:"Capture DigiSonde telemetry during ascent", groundStep2:"Track", groundStep2Text:"Feed real-time observations to the sounding workstation", groundStep3:"Operate", groundStep3Text:"Use rugged portable hardware or a fixed station configuration", portableCaption:"Portable field ground-station configuration", fixedCaption:"Fixed receiving / GPS antenna installation",
    softwareKicker:"DIGIMON® GROUND STATION & SOUNDING SOFTWARE", softwareTitle:"The operational interface for a sounding campaign", softwareText:"DigiMon brings sounding operations and profile review into one interface. The supplied software screen includes functions for starting a new sounding, loading a simulation, generating TEMP output and comparing ascents or profiles.", softwareF1:"New sounding workflow", softwareF2:"Load simulation", softwareF3:"Generate TEMP", softwareF4:"Compare ascents", softwareF5:"Compare profiles", softwareF6:"User and system settings",
    chainKicker:"MEASUREMENT FLOW", chainTitle:"From the balloon to usable meteorological data", chain1:"Balloon ascent", chain1Text:"DigiSonde rises through the atmosphere", chain2:"PTU + GNSS", chain2Text:"Atmospheric and position observations", chain3:"Radio downlink", chain3Text:"Telemetry transmitted to the ground", chain4:"Ground station", chain4Text:"Receiving and station hardware", chain5:"DigiMon", chain5Text:"Sounding, comparison and output workflow",
    fieldKicker:"FIELD & COMPARATIVE TESTING", fieldTitle:"Hardware shown in real sounding preparation and test environments", fieldLead:"These photographs are from Upper Air Observers development and field work. One image shows comparative preparation with a GRAW radiosonde; no performance claim is implied by the photograph.", fieldCap1:"Balloon preparation before sounding", fieldCap2:"Comparative preparation with a GRAW radiosonde", fieldCap3:"Portable station hardware and DigiSonde units", fieldCap4:"Field receiving antenna setup",
    appKicker:"APPLICATION AREAS", appTitle:"Upper-air measurements for operational weather and atmospheric work", appLead:"The supplied UAO catalogue identifies meteorology, transportation and energy as application areas, with sounding data supporting organizations such as meteorological institutes, airports and airlines, transport authorities and renewable-energy operators.", app1:"Meteorology", app1Text:"Vertical atmospheric observations for operational analysis and forecasting workflows.", app2:"Transportation", app2Text:"Upper-air information relevant to aviation and other weather-sensitive transport operations.", app3:"Energy", app3Text:"Atmospheric observations for weather-sensitive energy and renewable-energy activities.",
    downloadsKicker:"DOCUMENTATION", downloadsTitle:"DigiSonde product material", downloadsLead:"The documents below are the supplied Upper Air Observers catalogues used as the technical source for this product introduction.", doc1:"DigiSonde catalogue — Persian", doc2:"DigiSonde applications — English", doc3:"DigiSonde specifications — English",
    contactKicker:"UPPER AIR OBSERVERS", contactTitle:"Upper-air observation systems from Tehran, Iran.", contactText:"For DigiSonde radiosondes, ground-station hardware, DigiMon software or technical cooperation, contact Upper Air Observers.", locationLabel:"LOCATION", location:"Tehran, Iran", webLabel:"WEB", companyLabel:"COMPANY", companyName:"Upper Air Observers / پایشگران جو بالا", footerLocation:"Tehran, Iran", backTop:"Back to top ↑"
  },
  fa: {
    skip:"رفتن به محتوای اصلی", brand:"پایشگران جو بالا", brandFa:"Upper Air Observers",
    navSystem:"سامانه", navRadiosonde:"دیجی‌سوند", navGround:"ایستگاه زمینی", navSoftware:"دیجی‌مان", navField:"فعالیت میدانی", navDownloads:"دانلودها", navContact:"تماس",
    heroKicker:"سامانه‌های سونداژ جو بالا", heroTitle:"دیجی‌سوند.<br>از پرتاب بالن تا پروفیل جو.", heroLead:"یک زنجیره کامل پایش جو بالا شامل رادیوسوند دیجی‌سوند، سخت‌افزار دریافت میدانی و نرم‌افزار ایستگاه زمینی دیجی‌مان.", heroPrimary:"مشاهده سامانه", heroSecondary:"مشاهده کاتالوگ‌ها", fact1:"رادیوسوند دیجی‌سوند", fact2:"سخت‌افزار ایستگاه زمینی", fact3:"نرم‌افزار دیجی‌مان",
    systemKicker:"یک زنجیره کامل سونداژ", systemTitle:"رادیوسوند، سخت‌افزار دریافت و نرم‌افزار سونداژ؛ اجزای یک سامانه یکپارچه.", systemLead:"دیجی‌سوند پارامترهای جوی را در ارتفاع اندازه‌گیری و داده‌ها را از طریق رادیو ارسال می‌کند. ایستگاه زمینی سیگنال را دریافت می‌کند و دیجی‌مان فرآیند عملیاتی سونداژ، مقایسه پروفیل‌ها و تولید TEMP را پشتیبانی می‌کند.",
    sondeTag:"ابزار پروازی", sondeCardTitle:"رادیوسوند DigiSonde®", sondeCardText:"اندازه‌گیری PTU و GNSS با حمل توسط بالن برای تشکیل پروفیل عمودی جو در طول صعود.", learnSonde:"جزئیات محصول ←",
    groundTag:"سخت‌افزار میدانی", groundCardTitle:"ایستگاه زمینی", groundCardText:"آنتن‌های دریافت، تجهیزات ایستگاه و سخت‌افزار قابل حمل برای دریافت بلادرنگ تله‌متری رادیوسوند.", learnGround:"جزئیات سخت‌افزار ←",
    softwareTag:"عملیات و داده", softwareCardTitle:"نرم‌افزار DigiMon®", softwareCardText:"کنترل سونداژ، شبیه‌سازی، تولید TEMP و مقایسه صعودها و پروفیل‌ها در یک رابط عملیاتی.", learnSoftware:"جزئیات نرم‌افزار ←",
    dsKicker:"DIGISONDE®", dsTitle:"تله‌متری جو بالا برای اندازه‌گیری PTU و باد", dsText:"دیجی‌سوند توسط بالن هواشناسی به لایه‌های بالاتر جو حمل می‌شود، پارامترهای جوی را اندازه‌گیری کرده و داده‌ها را از طریق رادیو به ایستگاه زمینی ارسال می‌کند. فشار، دما، رطوبت نسبی و باد برای تشکیل پروفیل عمودی جو به‌کار می‌روند.", actualProduct:"تصویر واقعی محصول", pressureRange:"هکتوپاسکال بازه فشار", temperatureRange:"درجه سلسیوس بازه دما", humidityRange:"درصد بازه رطوبت نسبی", measurementRate:"نرخ اندازه‌گیری", ptuHead:"اندازه‌گیری PTU", pressure:"فشار", temperature:"دما", humidity:"رطوبت نسبی", txHead:"تله‌متری و مشخصات عمومی", frequency:"فرکانس", output:"توان خروجی", modulation:"مدولاسیون", weight:"وزن", inclBattery:"با احتساب باتری", specNote:"مشخصات نمایش‌داده‌شده از کاتالوگ ارائه‌شده دیجی‌سوند استخراج شده‌اند.",
    groundKicker:"سخت‌افزار ایستگاه زمینی", groundTitle:"برای دریافت رادیوسوند در چیدمان ثابت و قابل حمل میدانی", groundText:"زنجیره کامل سونداژ شامل آنتن دریافت لینک پایین، تجهیزات ایستگاه زمینی و آنتن GPS است. تصاویر زیر تجهیزات پایشگران جو بالا را در پیکربندی قابل حمل میدانی و یک نصب ثابت نشان می‌دهند.", groundStep1:"دریافت", groundStep1Text:"دریافت تله‌متری دیجی‌سوند در طول صعود", groundStep2:"رهگیری", groundStep2Text:"ارسال داده بلادرنگ به ایستگاه کاری سونداژ", groundStep3:"عملیات", groundStep3Text:"استفاده از سخت‌افزار مقاوم قابل حمل یا پیکربندی ثابت", portableCaption:"پیکربندی قابل حمل ایستگاه زمینی", fixedCaption:"نصب ثابت آنتن دریافت / GPS",
    softwareKicker:"نرم‌افزار ایستگاه زمینی و سونداژ DIGIMON®", softwareTitle:"رابط عملیاتی برای یک عملیات سونداژ", softwareText:"دیجی‌مان عملیات سونداژ و بررسی پروفیل‌ها را در یک محیط یکپارچه فراهم می‌کند. تصویر نرم‌افزار ارائه‌شده شامل شروع سونداژ جدید، بارگذاری شبیه‌سازی، تولید TEMP و مقایسه صعودها و پروفیل‌ها است.", softwareF1:"فرآیند سونداژ جدید", softwareF2:"بارگذاری شبیه‌سازی", softwareF3:"تولید TEMP", softwareF4:"مقایسه صعودها", softwareF5:"مقایسه پروفیل‌ها", softwareF6:"تنظیمات سامانه و کاربران",
    chainKicker:"جریان اندازه‌گیری", chainTitle:"از بالن تا داده هواشناسی قابل استفاده", chain1:"صعود بالن", chain1Text:"دیجی‌سوند در جو صعود می‌کند", chain2:"PTU + GNSS", chain2Text:"اندازه‌گیری‌های جوی و موقعیت", chain3:"لینک رادیویی", chain3Text:"ارسال تله‌متری به سطح زمین", chain4:"ایستگاه زمینی", chain4Text:"آنتن و تجهیزات دریافت", chain5:"دیجی‌مان", chain5Text:"سونداژ، مقایسه و تولید خروجی",
    fieldKicker:"آزمون‌های میدانی و مقایسه‌ای", fieldTitle:"تجهیزات در محیط واقعی آماده‌سازی سونداژ و آزمون", fieldLead:"این تصاویر مربوط به توسعه و فعالیت‌های میدانی پایشگران جو بالا هستند. در یکی از تصاویر آماده‌سازی مقایسه‌ای با یک رادیوسوند GRAW دیده می‌شود؛ این تصویر به‌تنهایی بیانگر ادعای عملکردی نیست.", fieldCap1:"آماده‌سازی بالن پیش از سونداژ", fieldCap2:"آماده‌سازی مقایسه‌ای با رادیوسوند GRAW", fieldCap3:"تجهیزات ایستگاه قابل حمل و واحدهای دیجی‌سوند", fieldCap4:"چیدمان آنتن دریافت در میدان",
    appKicker:"حوزه‌های کاربرد", appTitle:"اندازه‌گیری جو بالا برای عملیات هواشناسی و فعالیت‌های جوی", appLead:"کاتالوگ ارائه‌شده UAO هواشناسی، حمل‌ونقل و انرژی را به‌عنوان حوزه‌های کاربرد معرفی می‌کند و به استفاده از داده‌های هواشناسی توسط مؤسسات هواشناسی، فرودگاه‌ها و خطوط هوایی، مجموعه‌های حمل‌ونقل و فعالان انرژی‌های تجدیدپذیر اشاره دارد.", app1:"هواشناسی", app1Text:"مشاهدات عمودی جو برای تحلیل عملیاتی و فرآیندهای پیش‌بینی.", app2:"حمل‌ونقل", app2Text:"اطلاعات جو بالا برای هوانوردی و سایر عملیات حمل‌ونقل وابسته به شرایط جوی.", app3:"انرژی", app3Text:"مشاهدات جوی برای فعالیت‌های انرژی و انرژی‌های تجدیدپذیر حساس به هوا.",
    downloadsKicker:"مستندات", downloadsTitle:"مستندات محصول دیجی‌سوند", downloadsLead:"اسناد زیر کاتالوگ‌های ارائه‌شده پایشگران جو بالا هستند و به‌عنوان منبع فنی این معرفی محصول استفاده شده‌اند.", doc1:"کاتالوگ دیجی‌سوند — فارسی", doc2:"کاربردهای دیجی‌سوند — انگلیسی", doc3:"مشخصات دیجی‌سوند — انگلیسی",
    contactKicker:"پایشگران جو بالا", contactTitle:"سامانه‌های پایش جو بالا از تهران، ایران.", contactText:"برای رادیوسوند دیجی‌سوند، سخت‌افزار ایستگاه زمینی، نرم‌افزار دیجی‌مان یا همکاری فنی با پایشگران جو بالا تماس بگیرید.", locationLabel:"موقعیت", location:"تهران، ایران", webLabel:"وب", companyLabel:"شرکت", companyName:"پایشگران جو بالا / Upper Air Observers", footerLocation:"تهران، ایران", backTop:"بازگشت به بالا ↑"
  }
};

const root=document.documentElement, body=document.body;
const langButtons=[...document.querySelectorAll('.lang-btn')];
function setLanguage(lang){
  const dict=translations[lang]||translations.en;
  root.lang=lang; root.dir=lang==='fa'?'rtl':'ltr'; body.classList.toggle('fa',lang==='fa');
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k]!==undefined)el.innerHTML=dict[k]});
  langButtons.forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));
  try{localStorage.setItem('uao-lang',lang)}catch(e){}
}
langButtons.forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
const menuBtn=document.querySelector('.menu-toggle'), nav=document.querySelector('.main-nav');
menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
document.getElementById('year').textContent=new Date().getFullYear();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
let preferred='en';try{preferred=localStorage.getItem('uao-lang')||(navigator.language?.toLowerCase().startsWith('fa')?'fa':'en')}catch(e){}
setLanguage(preferred);
